services:
  web:
    build: web
    image: gps4pets/n7m-web
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - api
      - ui
    mem_limit: 100m
  ui:
    build: ui
    image: gps4pets/n7m-ui
    restart: always
    mem_limit: 100m
  api:
    build: api
    image: gps4pets/n7m-api
    restart: always
    environment:
      - PGPASSWORD=n7m-geocoding
      - WEB_CONCURRENCY=2
    depends_on:
      - gis
    mem_limit: 200m
  feed:
    build: feed
    image: gps4pets/n7m-feed
    depends_on:
      - gis
    environment:
      - PGPASSWORD=n7m-geocoding
      - OSM_FILENAME=germany-latest.osm.pbf
      - NOMINATIM_REPLICATION_URL=https://download.geofabrik.de/europe/germany-updates
      - NOMINATIM_REPLICATION_MAX_DIFF=3000
      - NOMINATIM_REPLICATION_UPDATE_INTERVAL=86400
    volumes:
      - ./data:/data/
  gis:
    build: gis
    image: gps4pets/n7m-gis
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=n7m-geocoding
    volumes:
      - ./pgdata:/var/lib/postgresql/data
