services:
  web:
    build:
      context: /opt/n7m/web
      dockerfile: /opt/n7m/web/Dockerfile
    image: gps4pets/n7m-web
    restart: always
    ports:
      - "8080:80"
    healthcheck:
      test: "curl -f http://localhost"
    depends_on:
      - api
      - ui
    mem_limit: 100m
    networks:
      - osm_bridge
  ui:
    build:
      context: /opt/n7m/ui
      dockerfile: /opt/n7m/ui/Dockerfile
    image: gps4pets/n7m-ui
    restart: always
    mem_limit: 100m
    healthcheck:
      test: "curl -f http://localhost"
    networks:
      - osm_bridge
  api:
    build:
      context: /opt/n7m/api
      dockerfile: /opt/n7m/api/Dockerfile
    image: gps4pets/n7m-api
    restart: always
    environment:
      - PGPASSWORD=n7m-geocoding
      - WEB_CONCURRENCY=2
    depends_on:
      - gis
    healthcheck:
      test: "curl -f http://localhost:8000"
    mem_limit: 200m
    networks:
      - osm_bridge
  feed:
    build:
      context: /opt/n7m/feed
      dockerfile: /opt/n7m/feed/Dockerfile
    image: gps4pets/n7m-feed
    depends_on:
      - gis
    environment:
      - PGPASSWORD=n7m-geocoding
      - OSM_FILENAME=germany-latest.osm.pbf
      - NOMINATIM_REPLICATION_URL=https://download.geofabrik.de/europe/germany-updates
      - NOMINATIM_REPLICATION_MAX_DIFF=3000
      - NOMINATIM_REPLICATION_UPDATE_INTERVAL=86400
    volumes:
      - /opt/n7m/data:/data/
    networks:
      - osm_bridge
  gis:
    build:
      context: /opt/n7m/gis
      dockerfile: /opt/n7m/gis/Dockerfile
    image: gps4pets/n7m-gis
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=n7m-geocoding
    healthcheck:
      test: pg_isready -h gis -U postgres
      interval: 60s
      retries: 2
      timeout: 10s
    volumes:
      - /opt/n7m/pgdata:/var/lib/postgresql/data
    networks:
      - osm_bridge
networks:
  osm_bridge:
  
