services:
  web:
    image: gps4pets/n7m-web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
      - ui
    mem_limit: 100m
  ui:
    image: gps4pets/n7m-ui
    restart: always
    mem_limit: 100m
  api:
    image: gps4pets/n7m-api
    restart: always
    depends_on:
      - gis
    environment:
      - PGPASSWORD=n7m-geocoding
      - WEB_CONCURRENCY=4
  gis:
    image: gps4pets/n7m-gis
    restart: always
    environment:
      - POSTGRES_PASSWORD=n7m-geocoding
    volumes:
      - ./pgdata:/var/lib/postgresql/data
