services:
  feed:
    image: GPS4PETS/n7m-feed
    depends_on:
      - gis
    environment:
      - PGPASSWORD=n7m-geocoding
      - OSM_FILENAME=north-america-latest.osm.pbf
      - NOMINATIM_FLATNODE_FILE=/data/flatnode.file
    command: setup
    volumes:
      - ./data:/data/
    shm_size: 1gb
  gis:
    image: GPS4PETS/n7m-gis
    restart: always
    environment:
      - POSTGRES_PASSWORD=n7m-geocoding
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    shm_size: 1gb
